### ISSUE TITLE
Adjustments german translation

### ISSUE THREAD

**Issue by YvesR** [WebDataRocks/pivot-localizations#16]
Hello,

I do not know if you like forks and PR for adjustments. 
But German translations need some fixes. I did not checked 100%, but already made just fixes.

So here is the corrected file.
[de.json.zip](https://github.com/WebDataRocks/pivot-localizations/files/6618752/de.json.zip)

If you accept PR, I can do instead.

Bye Yves

**Comment by YvesR** [comment]
Add: In German translation many window sizes do not fit.
I did modify the theme for this purpose, but do you also like to get those fixes or you don't care and I do this in my fork only :) ?

**Comment by mhalaida** [comment]
Hi @YvesR,

Thank you very much for your feedback!

We've merged your changes into master. If you have any other localization suggestions in the future, feel free to provide them via pull requests, it will be highly appreciated.

Speaking of custom styles, we recommend keeping them local, but thank you for the heads up – we'll look into the styling conflicts on our side!

Regards,
Mykhailo
