### ISSUE TITLE
considering chinese?

### ISSUE THREAD

**Issue by everast2015** [WebDataRocks/pivot-localizations#8]
is considering about chinese?

**Comment by tsshn** [comment]
Hello,

Thank you for your question.

The file providing Chinese localization has been added to the pivot-localizations repository.

The file itself can be found by the link: https://github.com/WebDataRocks/pivot-localizations/blob/master/zh.json.

More information about how to adjust localization of the component: https://www.webdatarocks.com/doc/language-localization/.

Kind Regards,
Illia

**Comment by everast2015** [comment]
@tsshn 
 thank you so much

**Comment by everast2015** [comment]
i have another question?when does support vuejs framework?

**Comment by tsshn** [comment]
Hello,

We are happy to announce that a Vue wrapper is added to the new version of WebDataRocks Pivot Table. [Check it out!](https://github.com/WebDataRocks/pivot-vue)

More information about changes provided with the update can be found here: https://www.webdatarocks.com/blog/webdatarocks-1-2-0-top-release-highlights/.

You are welcome to update the component.

Regards,
Illia
